### ISSUE TITLE
请看详情描述

### ISSUE THREAD

**Issue by jtsang4** [tmaccs/JD_miaosha#1]
你好：
    请尽快更改你的京东密码，我看到你的秒杀脚本里有一个账号密码，试着登陆了一下发现竟然是有效的，可以直接进入资产页面，你这个有点粗心啊……快点改密码吧……

**Comment by tmaccs** [comment]
非常感谢！最近总是收到京东的验证码，还觉得奇怪，自己并没有申请这些验证码..完全没想到这上面。谢谢提醒！

祝工作顺利！



在 2017年10月24日，上午10:23，Arthur <notifications@github.com<mailto:notifications@github.com>> 写道：


你好：
请尽快更改你的京东密码，我看到你的秒杀脚本里有一个账号密码，试着登陆了一下发现竟然是有效的，你这个有点粗心啊……快点改密码吧……

**Comment by jtsang4** [comment]
哈哈，不客气
